title: FINA 4380 for Fall 2022
author: Richard Herron
logo: DMSB_100th_LogoMark_CMYK_Horiz.jpg

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles: 
  - references.bib

repository:
  url: https://github.com/richardcherron/fina-4380-2022-fall
  path_to_book: Notebooks
html:
  use_issues_button: true
  use_edit_page_button: true
